### ISSUE TITLE
No match found when pattern contains parentheses

### ISSUE THREAD

**Issue by codestothestars** [sindresorhus/globby#74] opened 2018-02-14 19:56 UTC
If the specified pattern contains parentheses, no match is ever found, even when the path exists.

```javascript
const globby = require('globby');

(async () => {
  const glob = './any(directory)/file.txt';
  const paths = await globby(glob);

  console.log(paths); //always logs an empty array
})();
```

Tested environments...

macOS 10.13.3
globby 8.0.0
node 7.10.0
npm 5.6.0

Windows 10.0.16299 Pro
globby 8.0.0
node 9.5.0
npm 5.6.0

**Comment by kevva** [comment] 2018-02-14 20:29
You have to escape the parentheses since those are "wildcards" in the glob syntax. You can read more about them (extended globs) at http://www.linuxjournal.com/content/bash-extended-globbing.

**Comment by codestothestars** [comment] 2018-02-14 21:46
@kevva I checked out that link and it doesn't seem like my example pattern contains extended syntax, as the parentheses are not preceded by any of ?, *, +, @, or !. I assumed the error was mine until I tried the same pattern with [node-glob](https://github.com/isaacs/node-glob) and it worked as I expected. That module has a `noext` option as well and claims to use the extended syntax by default, so I thought this might be a bug in globby.

Regardless, thank you for the info and your time. I'll continue using globby and set `noext: true` as you suggested, as I don't need the extended syntax and much prefer the Promise API of globby.

**Comment by kevva** [comment] 2018-02-14 21:53
@codestothestars, you could open an issue at https://github.com/mrmlnc/fast-glob about it. Definitely sounds like a bug.

**Comment by codestothestars** [comment] 2018-02-14 22:59
@kevva Actually, I just tested and even when specifying `noext: true` I am still not getting a match for my example pattern above. So it seems like there is something wrong here.

**Comment by kevva** [comment] 2018-02-14 23:53
I just tried the following and it worked fine:

```js
await globby('./tmp(asd)/a.tmp', {noext: true});
//=> ['./tmp(asd)/a.tmp']
```

**Comment by codestothestars** [comment] 2018-02-15 16:19
I keep thinking I must be crazy, but I created a very simple example and am still reproducing the problem. See my repository at [codestothestars/globby-test](https://github.com/codestothestars/globby-test/tree/ab0892930ac1ba7262d9534c28e44ee3c131a3b6). In the environments I noted, the issue occurs regardless of whether `ext: true` is specified.

Am I missing something silly here that you can see? If not, can you let me know what environment you're running in so I can try to troubleshoot further?

**Comment by mrmlnc** [comment] 2018-02-15 19:23
So, this is `fast-glob` issue. Looks like a bug in the `micromatch` method `mekeRe` or *something* inside micromatch (we use `makeRe`). I think we can reopen this issue or create it in the `fast-glob` repository.

```js
const micromatch = require('micromatch');

const matcherNoExt = micromatch.matcher('./test(dir)/foo.txt', { noext: true });
const matcher = micromatch.matcher('./test(dir)/foo.txt');

const reNoExt = micromatch.makeRe('./test(dir)/foo.txt', { noext: true });
const re = micromatch.makeRe('./test(dir)/foo.txt');

const cases = [
    'default',
    micromatch('./test(dir)/foo.txt', './test(dir)/foo.txt'),
    micromatch('./test(dir)/foo.txt', './test(dir)/foo.txt', { noext: true }),
    'match',
    micromatch.match('./test(dir)/foo.txt', './test(dir)/foo.txt'),
    micromatch.match('./test(dir)/foo.txt', './test(dir)/foo.txt', { noext: true }),
    'matcher',
    matcherNoExt('./test(dir)/foo.txt'), // false
    matcher('./test(dir)/foo.txt'), // false,
    'regexp',
    reNoExt.test('./test(dir)/foo.txt'), // false
    re.test('./test(dir)/foo.txt') // false
]

console.dir(cases, { colors: true });
```

**Output**

```
[
    'default',
    [ 'test(dir)/foo.txt' ],
    [ 'test(dir)/foo.txt' ],

    'match',
    [ 'test(dir)/foo.txt' ],
    [ 'test(dir)/foo.txt' ],

    'matcher',
    false,
    false,

    'regexp',
    false,
    false
]
```

**Comment by kevva** [comment] 2018-02-15 19:32
Yup, seems like it escapes stuff inside the parens `^(?:(?:(?:\.(?:\/|\\))(?=.))?test\(\dir\)\/foo\.txt)$` (note the `\(\dir\)`). `\d` in this case will match digits instead of the `d` character.

**Comment by mrmlnc** [comment] 2018-02-15 19:55
Related issue https://github.com/micromatch/micromatch/issues/116.

**Comment by mrmlnc** [comment] 2018-02-18 19:07
Should be fixed by `micromatch@3.1.6`. Just reinstall `node_modules` by `npm i --force`, for example.

**Comment by pvdlg** [comment] 2018-02-19 22:37
@codestothestars can you confirm the issue is solved?

**Comment by codestothestars** [comment] 2018-02-20 00:44
@pvdlg I added `micromatch@3.1.6` as a dependency in my [test repository](https://github.com/codestothestars/globby-test/tree/7bdf52e6bedae31331740ada6f7e7f1de5557813) (which I had to, because fast-glob's dependency on micromatch hasn't been updated yet) and it does seem to improve the situation, although I'm not sure if it's completely fixed. Now my pattern matches the `test(dir)` directory if I specify `noext: true` in my call to globby, which is great. However, it still does not match when noext is false or unspecified. Unless I'm wrong and all parentheses are considered to be extended syntax, I would expect it to match even when noext is not true.

**Comment by pvdlg** [comment] 2018-02-20 16:47
The `micromatch` update is just a patch, so you don't have to change anything in your dependencies, just re-install your `node_modules` and the last version will automatically 0be used (as all the dependencies in the chain use `^`).

Can you re-clarify exactly what doesn't work? Please provide:
- Your files/folder tree
- The patterns and option you are passing to `globby`
- The result you get and the one you expect

**Comment by codestothestars** [comment] 2018-02-20 17:22
Regarding the dependency update, am I correct that the relevant dependency chain here is `globby -> fast-glob -> micromatch`? If so, fast-glob appears to pin the fully qualified version. I'm looking [here](https://github.com/mrmlnc/fast-glob/blob/5ed6366abee5d86655e456c5d2807f057475b7ca/package.json).

My directory structure is as follows:

```
├── test(dir)
    └── foo.txt
├── testdir
    └── bar.txt
```

From the root directory, I am running the following script:
```javascript
const globby = require('globby');

(async () => {
    console.log(await globby('./test(dir)/foo.txt'));
    console.log(await globby('./test(dir)/foo.txt', { noext: true }));
    console.log(await globby('./testdir/bar.txt'));
    console.log(await globby('./testdir/bar.txt', { noext: true }));
})();
```

From there I receive the following output:
```
[]
[ './test(dir)/foo.txt' ]
[ './testdir/bar.txt' ]
[ './testdir/bar.txt' ]
```

But the first (empty) result seems incorrect to me. I expected to see the following output:
```
[ './test(dir)/foo.txt' ]
[ './test(dir)/foo.txt' ]
[ './testdir/bar.txt' ]
[ './testdir/bar.txt' ]
```

I have this exact setup in my [test repository](https://github.com/codestothestars/globby-test/tree/7bdf52e6bedae31331740ada6f7e7f1de5557813) if you'd like to reproduce this yourself.

**Comment by mrmlnc** [comment] 2018-02-20 17:24
Oh, sorry I forgot that the `fast-glob` package have a fully qualified dependencies. So, I'll publish the new version of `fast-glob` very soon.

**Comment by mrmlnc** [comment] 2018-02-25 16:30
Should be fully fixed by `fast-glob@2.1.0` where we allow to use minor-free updates for dependencies. 

Sorry for delay and this situation :taco:

**Comment by kevva** [comment] 2018-03-05 16:23
@codestothestars, I'm going to close this issue as fixed. Please comment if it's still failing for you.

**Closed by kevva** 2018-03-05 16:23 UTC

**Comment by codestothestars** [comment] 2018-03-05 22:56
I've confirmed that this is now working correctly. Thank you so much, everyone!
