### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by xidianheyanjun** [sindresorhus/globby#234] opened 2022-06-07 07:06 UTC
how to solve this problem?

E:\project\dragon-carving-server\node_modules\egg-ts-helper\node_modules\globby\index.js:28
        } catch {
                ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\project\dragon-carving-server\node_modules\egg-ts-helper\dist\utils.js:7:42)

**Comment by sindresorhus** [comment] 2022-06-07 08:22
Duplicate of #169

**Closed by sindresorhus** 2022-06-07 08:22 UTC
