### ISSUE TITLE
Version 8.0.0 needs git executable on install

### ISSUE THREAD

**Issue by code-chris** [sindresorhus/globby#72] opened 2018-02-13 13:39 UTC
Since version 8.0.0 this library or one of its dependencies needs the "git" executable on npm install, which breaks several of our CI builds. I downgraded to 7.1.1 for now.

Is it possible to remove this dependency to git?

Node: 8.9.4
NPM: 5.6.0
OS: Windows Server 2016

**Comment by sindresorhus** [comment] 2018-02-13 13:49
Caused by this one: https://github.com/mrmlnc/fast-glob/blob/16befe373e975fe6bb6ba9d1ba1006640f31f18a/package.json#L54

// @mrmlnc

**Comment by mrmlnc** [comment] 2018-02-13 15:14
Yeap, I can publish this package as `readdir-enhanced-tmp`. Unfortunately, I haven't access to `readdir-enhanced` package. Will be fixed today.

**Comment by kevva** [comment] 2018-02-14 12:26
@mrmlnc, awesome!

**Closed by kevva** 2018-02-14 12:26 UTC
