### ISSUE TITLE
No match found when pattern contains parentheses

### ISSUE THREAD

**Issue by zrh122** [sindresorhus/globby#134] opened 2019-08-15 06:52 UTC
version `globby@10.0.1`

directory structure:
```
├── tmp(asd)
    └── a.tmp
```
from above directory, run script:
```js
const globby = require('globby');
const paths = globby.sync('./tmp(asd)/a.tmp',  {noext: true});
console.log(paths);
```
the result is empty.

related info: [comment](https://github.com/sindresorhus/globby/issues/74#issuecomment-365784160)

**Comment by sindresorhus** [comment] 2019-08-18 17:54
This sounds like a `fast-glob` regression. As it was fixed last year: https://github.com/sindresorhus/globby/issues/74#issuecomment-368323132

// @mrmlnc

**Comment by zrh122** [comment] 2019-08-18 18:33
Thanks for relpy, and I make a mistake. As globby upgrade fast-glob package to v3, I should use new option:
```js
const globby = require('globby');
const paths = globby.sync('./tmp(asd)/a.tmp',  {extglob: false});
console.log(paths);
```
but the result is also empty.

**Comment by mrmlnc** [comment] 2019-08-18 19:16
Yeah, this is a known issue.

0. https://github.com/micromatch/picomatch/issues/7
1. https://github.com/mrmlnc/fast-glob#why-are-parentheses-match-wrong

**Comment by zrh122** [comment] 2019-08-18 19:44
So `{extglob: false}` is not work well, what i should do is that:
```js
globby.sync('./tmp\\(asd\\)/a.tmp');
```
🙁but the result is also empty. @mrmlnc 
Maybe you can tell me how to do make things work well. 🙏

**Comment by mrmlnc** [comment] 2019-08-19 06:16
Unfortunately, it looks like a bug:

```js
fg.sync('styles/\\(tmp\\)/*') → ['styles/(tmp)/a.tmp']
fg.sync('styles/\\(tmp\\)/a.tmp') → []
```

Please, create issue on the `fast-glob` repository.

**Comment by zrh122** [comment] 2019-08-19 07:58
Thanks for your relpy @mrmlnc , I created an [issue](https://github.com/mrmlnc/fast-glob/issues/223) on the `fast-glob` for it.

**Comment by mrmlnc** [comment] 2019-10-06 13:20
Should be fixed with `fast-glob@3.1.0`.

**Closed** 2019-10-07 00:58 UTC
